version: 2
updates:
  # Maintain dependencies for Cargo
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'daily'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
