name: js

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Run yarn dedupe
        run: yarn dedupe --check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Check formatting of project files
        run: yarn format:diff

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            javascript:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
      - name: Run tests
        run: yarn test
        if: ${{ steps.filter.outputs.javascript == 'true' }}

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            ts:
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.js'
      - name: Typecheck files
        run: yarn typecheck
        if: ${{ steps.filter.outputs.ts == 'true' }}
