name: js

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - name: Run yarn dedupe
        run: yarn dedupe --check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - uses: actions/cache@v2.1.6
        with:
          path: |
            node_modules
            */**/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            js:
              - '**/*.js'
      - name: Check formatting of project files
        run: yarn format:diff
        if: ${{ steps.filter.outputs.js == 'true' }}

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - uses: actions/cache@v2.1.6
        with:
          path: |
            node_modules
            */**/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            ts:
              - '**/*.ts?x'
      - name: Typecheck TypeScript files
        run: yarn typecheck
        if: ${{ steps.filter.outputs.ts == 'true' }}
